### PR TITLE
feat: use built-in `import.meta.resolve` function

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by sheerlox** [comment]
Hi @yordis, sorry for the delay, I have been under a very high workload lately.

The proposed solution  only works for Node v18 and above, so we need to explicitly drop support for previous versions, which is a breaking change. I've renamed the PR title and added the breaking change to the description.

**Comment by sheerlox** [comment]
Hi @yordis, sorry for the delay, I have been under a very high workload lately.

`import.meta.resolve` still requires a flag until Node v20.6, so the library would stop working for previous versions of Node, which is undesired.

Since v20.6, it doesn't require the `--experimental-import-meta-resolve` flag, but the `parentURL` parameter still does, which means importing from a specific directory won't work out-of-the-box (`npm run test:nested` shows that the `parentURL` parameter is not taken into account).

We could merge this PR into the unstable `beta` distribution channel, so you could use it with the flaws I just described until the feature is considered stable and previous versions are out of LTS.

See https://nodejs.org/docs/latest-v20.x/api/esm.html#importmetaresolvespecifier

image

**Comment by yordis** [comment]
I trust your decision, for my package, I am OK using `alpha` channels until it becomes stable enough. So let me know!

Personally, I would only support Node LTS+, but I also do not have packages as popular as the one you maintain, so easier for me to say.

**Review by sheerlox — APPROVED** [review]

**Comment by sheerlox** [comment]
@yordis it's out! please let me know if it effectively solved your issue when you get the time :smiley:

**Comment by yordis** [comment]
It seems to work like a champ!

**Comment by yordis** [comment]
@sheerlox now with node v22, would be OK to have a regular release?

**Pull request merged**
